name: Release
on:
  push:
    branches: [main]
    paths:
      - "package.json"

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install
          sudo npm install -g electron@32.0.0 electron-builder
          npm rebuild sqlite3 --build-from-source

      - name: Build and release Mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: false
        run: |
          npm run build
          electron-builder --mac --x64 --arm64 --publish=always

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsecret-1-dev

      - name: Install dependencies
        env:
          CFLAGS: "-Wno-implicit-fallthrough -Wno-maybe-uninitialized -Wno-misleading-indentation -Wno-stringop-overflow"
          CXXFLAGS: "-Wno-implicit-fallthrough -Wno-maybe-uninitialized -Wno-misleading-indentation -Wno-stringop-overflow"
        run: |
          npm install
          sudo npm install -g electron@32.0.0 electron-builder
          npm rebuild sqlite3 --build-from-source

      - name: Build and release Linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: false
        run: |
          npm run build
          electron-builder --linux --x64 --publish=always

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        env:
          npm_config_build_from_source: false
        run: |
          npm install
          npm install -g electron@32.0.0 electron-builder

      - name: Build and release Windows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: false
        run: |
          npm run build
          electron-builder --win --x64 --publish=always
